version: '3'
services:
  world:
    build: 
      context: ./backend/world/
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/world/src:/usr/src/app/src
    environment:
      - MONGO_URL=mongodb://mongo:27017/world
      - ETHEREUM_URL=ws://ethereum-node:8545
    command: 'npm run dev'
    ports:
      - '9001:9001'
    depends_on:
      - ethereum-node
      - mongo
      - contracts

  contracts:
    build:
      context: ./backend/ethereum/
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/contracts
      - ETHEREUM_PROTOCOL=http
      - ETHEREUM_HOST=ethereum-node
    command: 'npm run start'
    ports:
      - '9002:9002'
    depends_on:
      - ethereum-node
      - mongo

  mongo:
    image: mongo:4.0.6
    ports:
      - 27017:27017

  ethereum-node:
    image: trufflesuite/ganache-cli:v6.4.2
    ports:
      - 8545:8545
