version: '3'
services:
  world:
    build: 
      context: ./backend/world/
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/world/src:/usr/src/app/src
      - ./backend/ethereum/build/contracts:/ethereum/build/contracts
    environment:
      - MONGO_URL=mongodb://world-mongo:27017/world
      - ETHEREUM_URL=ws://ethereum-node:8545
    command: 'npm run dev'
    ports:
      - '9001:9001'
    depends_on:
      - world-mongo
      - ethereum-node

  world-mongo:
    image: mongo:4.0.6
    volumes:
      - world-mongo-data:/data/db
    ports:
      - 27017:27017

  ethereum-node:
    image: trufflesuite/ganache-cli:v6.4.2
    ports:
      - 8545:8545

volumes:
  world-mongo-data:
