apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: contracts
  name: contracts
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: contracts
    spec:
      containers:
      - args:
        - npm
        - run
        - start
        env:
        - name: ETHEREUM_HOST
          value: ethereum-node
        - name: ETHEREUM_PROTOCOL
          value: http
        - name: MONGO_URL
          value: mongodb://mongo:27017/contracts
        image: contracts
        name: contracts
        ports:
        - containerPort: 9002
        resources: {}
      restartPolicy: Always
status: {}
