apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: world
  name: world
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: world
    spec:
      containers:
      - args:
        - npm
        - run
        - dev
        env:
        - name: CONTRACTS_URL
          value: http://contracts:9002
        - name: ETHEREUM_URL
          value: ws://ethereum-node:8545
        - name: MONGO_URL
          value: mongodb://mongo:27017/world
        image: kryha/world
        name: world
        ports:
        - containerPort: 9001
        resources: {}
      restartPolicy: Always
status: {}
