apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  creationTimestamp: null
  name: ganache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ganache
    spec:
      containers:
        - image: trufflesuite/ganache-cli
          name: ganache
          ports:
            - containerPort: 8545
          resources: {}
status: {}
