apiVersion: v1
kind: Service
metadata:
  namespace: default
  creationTimestamp: null
  name: ganache
spec:
  ports:
    - name: "http"
      port: 8545
      targetPort: 8545
  selector:
    io.kompose.service: ganache
status:
  loadBalancer:
    
